#!/usr/bin/env python3
"""Slices an Aseprite sprite sheet (PNG + hash JSON) into RGB565 frames.

Reads assets/ferret-sprite-sheet.json (Aseprite export, hash format) plus the
matching PNG, groups frames by animation (the tag in parentheses in the frame
name, e.g. "(Movement)"), scales with NEAREST and generates PROGMEM headers.

Two outputs:
  include/ferret_anim.h  - full animation set at 2.5x (80px), scene character
  include/ferret_game.h  - just the jump frames at 1.25x (40px), mini-game

Frames use the same transparency color key convention (0xF81F).

Artwork: "2D Pixel Art Ferret Sprites" by Elthen's Pixel Art Shop
(https://elthen.itch.io/2d-pixel-art-ferret-sprites).

Usage:
    python3 assets/aseprite_to_frames.py
"""
import json
import os
import re
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "assets", "ferret-sprite-sheet.json")
PNG_PATH = os.path.join(ROOT, "assets", "ferret-sprite-sheet.png")

TRANSPARENT_KEY = 0xF81F  # magenta (color key, not used in the artwork)
TAG_RE = re.compile(r"\(([^)]+)\)\s*(\d+)\.ase")

# Full scene animation set (2.5x -> 80px). (Aseprite tag, C identifier, mirror?)
ANIM_EXPORT = [
    ("Idle",      "ferret_idle",      False),
    ("Idle",      "ferret_idle_l",    True),
    ("Idle2",     "ferret_idle2",     False),
    ("Idle2",     "ferret_idle2_l",   True),
    ("Movement",  "ferret_walk",      False),
    ("Movement",  "ferret_walk_l",    True),
    ("Jump",      "ferret_jump",      False),
    ("Jump",      "ferret_jump_l",    True),
    ("Dig",       "ferret_dig",       False),  # used for eating AND burrowing
    ("Disappear", "ferret_disappear", False),
    ("Emerge",    "ferret_emerge",    False),
    ("Sleep",     "ferret_sleep",     False),
]

# Mini-game character (1.25x -> 40px): jump (Doodle) + walk/idle (Bolinha).
GAME_EXPORT = [
    ("Jump",     "ferret_g_jump",   False),
    ("Jump",     "ferret_g_jump_l", True),
    ("Movement", "ferret_g_walk",   False),
    ("Movement", "ferret_g_walk_l", True),
    ("Idle",     "ferret_g_idle",   False),
    ("Idle",     "ferret_g_idle_l", True),
]


def to_rgb565(r, g, b, a):
    if a < 128:
        return TRANSPARENT_KEY
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    if v == TRANSPARENT_KEY:
        v ^= 0x0020  # avoid an accidental collision with the color key
    return v


def slice_group(sheet, frames, scale, mirror):
    out = []
    w = h = None
    for _, fr in frames:
        crop = sheet.crop((fr["x"], fr["y"], fr["x"] + fr["w"], fr["y"] + fr["h"]))
        crop = crop.resize((int(round(fr["w"] * scale)), int(round(fr["h"] * scale))), Image.NEAREST)
        if mirror:
            crop = crop.transpose(Image.FLIP_LEFT_RIGHT)
        w, h = crop.size
        out.append([to_rgb565(*crop.getpixel((x, y))) for y in range(h) for x in range(w)])
    return out, w, h


def generate(sheet, groups, export, scale, out_path, prefix):
    fw = fh = None
    blocks = []
    for tag, ident, mirror in export:
        if tag not in groups:
            print(f"WARNING: tag '{tag}' not found, skipping", file=sys.stderr)
            continue
        frames_out, fw, fh = slice_group(sheet, groups[tag], scale, mirror)
        blocks.append((ident, frames_out, fw * fh))

    with open(out_path, "w") as f:
        f.write("// GENERATED by assets/aseprite_to_frames.py - do NOT edit by hand.\n")
        f.write(f"// Source: {os.path.basename(PNG_PATH)}\n")
        f.write("// Artwork: \"2D Pixel Art Ferret Sprites\" by Elthen's Pixel Art Shop\n")
        f.write("// https://elthen.itch.io/2d-pixel-art-ferret-sprites\n")
        f.write("#pragma once\n#include <cstdint>\n#include <pgmspace.h>\n\n")
        f.write(f"#define {prefix}FRAME_W {fw}\n")
        f.write(f"#define {prefix}FRAME_H {fh}\n")
        f.write(f"#define {prefix}FRAME_PIXELS {fw * fh}\n")
        f.write(f"#define {prefix}TRANSPARENT_KEY 0x{TRANSPARENT_KEY:04X}\n\n")
        for ident, frames_out, npix in blocks:
            n = len(frames_out)
            f.write(f"#define {ident.upper()}_FRAMES {n}\n")
            f.write(f"const uint16_t {ident}[{n}][{npix}] PROGMEM = {{\n")
            for fr in frames_out:
                f.write("  {" + ",".join(f"0x{p:04X}" for p in fr) + "},\n")
            f.write("};\n\n")

    total = sum(len(fr) * npix * 2 for _, fr, npix in blocks)
    print(f"OK: {out_path}  ({fw}x{fh}, {sum(len(fr) for _, fr, _ in blocks)} frames, ~{total // 1024} KB)")


def main() -> int:
    with open(JSON_PATH) as f:
        meta = json.load(f)
    sheet = Image.open(PNG_PATH).convert("RGBA")

    groups = {}
    for name, info in meta["frames"].items():
        m = TAG_RE.search(name)
        if not m:
            continue
        groups.setdefault(m.group(1), []).append((int(m.group(2)), info["frame"]))
    for tag in groups:
        groups[tag].sort(key=lambda t: t[0])

    generate(sheet, groups, ANIM_EXPORT, 2.5, os.path.join(ROOT, "include", "ferret_anim.h"), "FERRET_")
    generate(sheet, groups, GAME_EXPORT, 1.25, os.path.join(ROOT, "include", "ferret_game.h"), "FERRET_G_")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
