#!/usr/bin/env python3
"""Slices an Aseprite sprite sheet (PNG + hash JSON) into RGB565 frames.

Reads assets/ferret-sprite-sheet.json (Aseprite export, hash format) plus the
matching PNG, groups frames by animation (the tag in parentheses in the frame
name, e.g. "(Movement)"), scales with NEAREST and generates
include/ferret_anim.h with one PROGMEM array per animation.

Each animation becomes `const uint16_t <ident>[N][W*H] PROGMEM`, using the
same transparency color key convention as the rest of the project (0xF81F).

Usage:
    python3 assets/aseprite_to_frames.py
"""
import json
import os
import re
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "assets", "ferret-sprite-sheet.json")
PNG_PATH = os.path.join(ROOT, "assets", "ferret-sprite-sheet.png")
OUT_PATH = os.path.join(ROOT, "include", "ferret_anim.h")

SCALE = 2.5                  # 32x32 -> 80x80
TRANSPARENT_KEY = 0xF81F     # magenta (color key, not used in the artwork)

# (Aseprite tag, C identifier, mirror horizontally?)
EXPORT = [
    ("Idle",      "ferret_idle",      False),
    ("Idle",      "ferret_idle_l",    True),
    ("Idle2",     "ferret_idle2",     False),
    ("Idle2",     "ferret_idle2_l",   True),
    ("Movement",  "ferret_walk",      False),
    ("Movement",  "ferret_walk_l",    True),
    ("Jump",      "ferret_jump",      False),
    ("Jump",      "ferret_jump_l",    True),
    ("Dig",       "ferret_dig",       False),  # used for eating AND burrowing
    ("Disappear", "ferret_disappear", False),
    ("Emerge",    "ferret_emerge",    False),
    ("Sleep",     "ferret_sleep",     False),
]

TAG_RE = re.compile(r"\(([^)]+)\)\s*(\d+)\.ase")


def to_rgb565(r, g, b, a):
    if a < 128:
        return TRANSPARENT_KEY
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    if v == TRANSPARENT_KEY:
        v ^= 0x0020  # avoid an accidental collision with the color key
    return v


def main() -> int:
    with open(JSON_PATH) as f:
        meta = json.load(f)

    sheet = Image.open(PNG_PATH).convert("RGBA")

    # Group frames by tag, sorted by their numeric index.
    groups = {}
    for name, info in meta["frames"].items():
        m = TAG_RE.search(name)
        if not m:
            continue
        tag, idx = m.group(1), int(m.group(2))
        groups.setdefault(tag, []).append((idx, info["frame"]))
    for tag in groups:
        groups[tag].sort(key=lambda t: t[0])

    fw = fh = None
    blocks = []
    for tag, ident, mirror in EXPORT:
        if tag not in groups:
            print(f"WARNING: tag '{tag}' not found, skipping", file=sys.stderr)
            continue
        frames_out = []
        for _, fr in groups[tag]:
            crop = sheet.crop((fr["x"], fr["y"], fr["x"] + fr["w"], fr["y"] + fr["h"]))
            dw, dh = int(round(fr["w"] * SCALE)), int(round(fr["h"] * SCALE))
            crop = crop.resize((dw, dh), Image.NEAREST)
            if mirror:
                crop = crop.transpose(Image.FLIP_LEFT_RIGHT)
            w, h = crop.size
            fw, fh = w, h
            px = [to_rgb565(*crop.getpixel((x, y))) for y in range(h) for x in range(w)]
            frames_out.append(px)
        blocks.append((ident, frames_out, w * h))

    with open(OUT_PATH, "w") as f:
        f.write("// GENERATED by assets/aseprite_to_frames.py - do NOT edit by hand.\n")
        f.write(f"// Source: {os.path.basename(PNG_PATH)}\n")
        f.write("#pragma once\n#include <cstdint>\n#include <pgmspace.h>\n\n")
        f.write(f"#define FERRET_FRAME_W {fw}\n")
        f.write(f"#define FERRET_FRAME_H {fh}\n")
        f.write(f"#define FERRET_FRAME_PIXELS {fw * fh}\n")
        f.write(f"#define FERRET_TRANSPARENT_KEY 0x{TRANSPARENT_KEY:04X}\n\n")
        for ident, frames_out, npix in blocks:
            n = len(frames_out)
            f.write(f"#define {ident.upper()}_FRAMES {n}\n")
            f.write(f"const uint16_t {ident}[{n}][{npix}] PROGMEM = {{\n")
            for fr in frames_out:
                f.write("  {")
                f.write(",".join(f"0x{p:04X}" for p in fr))
                f.write("},\n")
            f.write("};\n\n")

    total = sum(len(fr) * npix * 2 for _, fr, npix in blocks)
    print(f"OK: {OUT_PATH}")
    print(f"  frame {fw}x{fh}, {sum(len(fr) for _, fr, _ in blocks)} frames, ~{total // 1024} KB flash")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
