#!/usr/bin/env python3
"""Converts an MP3 file into a C header (PROGMEM array) embedded in flash.

Usage:
    python3 assets/mp3_to_header.py <input.mp3> <symbol_name> [output.h]

Example:
    python3 assets/mp3_to_header.py ~/Downloads/tune.mp3 sleep_music_mp3 \
        include/sleep_music.h

Same idea as the sprite pipeline: assets become generated headers, with no
extra filesystem-upload step. The MP3 lives in PROGMEM and is decoded
straight from flash by ESP8266Audio (AudioFileSourcePROGMEM).
"""
import os
import sys


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__)
        return 1

    in_path = os.path.expanduser(sys.argv[1])
    symbol = sys.argv[2]
    out_path = sys.argv[3] if len(sys.argv) > 3 else f"include/{symbol}.h"

    with open(in_path, "rb") as f:
        data = f.read()

    lines = [
        "// GENERATED by assets/mp3_to_header.py - do NOT edit by hand.",
        f"// Source: {os.path.basename(in_path)} ({len(data)} bytes)",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
        f"const unsigned int {symbol}_len = {len(data)};",
        f"const unsigned char {symbol}[] PROGMEM = {{",
    ]

    row = []
    body = []
    for b in data:
        row.append(f"0x{b:02X},")
        if len(row) == 16:
            body.append("  " + "".join(row))
            row = []
    if row:
        body.append("  " + "".join(row))

    lines.extend(body)
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"OK: {out_path}  ({len(data)} bytes -> PROGMEM array '{symbol}')")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
