#!/usr/bin/env python3
"""Gzips the single-file React portal build and generates a C header (PROGMEM).

Usage:
    python3 assets/web_to_header.py

Reads web/dist/index.html, compresses it with gzip and writes
include/web_index.h containing `web_index_gz[]` + `web_index_gz_len`.
The WebServer serves the blob with Content-Encoding: gzip.
"""
import gzip
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "web", "dist", "index.html")
OUT = os.path.join(ROOT, "include", "web_index.h")


def main() -> int:
    with open(SRC, "rb") as f:
        raw = f.read()
    gz = gzip.compress(raw, 9)

    lines = [
        "// GENERATED by assets/web_to_header.py - do NOT edit by hand.",
        f"// React portal (single file), gzipped: {len(raw)} -> {len(gz)} bytes",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
        f"const unsigned int web_index_gz_len = {len(gz)};",
        "const unsigned char web_index_gz[] PROGMEM = {",
    ]
    body = []
    row = []
    for b in gz:
        row.append(f"0x{b:02X},")
        if len(row) == 16:
            body.append("  " + "".join(row))
            row = []
    if row:
        body.append("  " + "".join(row))
    lines.extend(body)
    lines.append("};")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"OK: {OUT}  ({len(raw)} -> {len(gz)} bytes gzip)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
